@echo off
echo Starting HomeServ (Production)...
cd /d "%~dp0app"

echo Building...
call npm run build

echo Starting VNC Proxy on port 3002...
start "HomeServ VNC Proxy" cmd /c "npx tsx vnc-server.ts"

echo Starting production server on port 3001...
npm run start
